package com.dosecerta.controller;

public class ImunizacaoController {
    
    //ADICIONAR IMUNIZACAO

    //ALTERAR IMUNIZACAO

    //EXCLUIR IMUNIZACAO

    //EXCLUIR TODAS AS IMUNIZACOES DE DETERMINADO PACIENTE

    //CONSULTAR TODAS AS IMUNIZACOES

    //CONSULTAR IMUNIZACAO POR ID

    //CONSULTAR IMUNIZACOES POR ID DO PACIENTE

    //CONSULTAR CONSULTAR IMUNIZACOES POR ID DO PACIENTE E INTERVALO DE APLICACAO

}
